Fixed survey buttons, trying to fix the table width
multiparty/web-mpc pull request #105
Opened 2019-02-08 19:16 UTC by globusharris

DO NOT MERGE

2019-02-11 19:35 UTC, globusharris commented
Ready to merge! I think!

2019-02-11 19:36 UTC, globusharris commented
Note that this is good enough for pacesetters demo but table width and submission still won't work for bwwc.

2019-02-11 20:07 UTC, lucyq commented
Ready for review @frederickjansen

2019-02-13 00:17 UTC, frederickjansen requested changes

2019-02-13 00:17 UTC, frederickjansen commented on client/app/controllers/tableController.js
> +    $('#instructions').css('max-width', '1153px');
Let me see if I can get rid of this hardcoded value.

2019-02-13 00:17 UTC, frederickjansen commented on client/app/controllers/tableController.js
> +    console.log("updating");
Please don't keep these console logs

2019-02-13 00:17 UTC, frederickjansen commented on client/app/controllers/tableController.js
> +      console.log(w);
Same thing here

2019-02-13 00:17 UTC, frederickjansen commented on client/app/controllers/tableController.js
> +      console.log(w);
Same thing here

2019-02-13 00:17 UTC, frederickjansen commented on client/index.html
> +      <span id="expand-table-button" class="arrow-down"></span>
This will break for BWWC, since their tables are supposed to start collapsed. I guess this should become a config option?

2019-02-13 03:10 UTC, merged

2019-02-13 03:10 UTC, frederickjansen commented
I'll merge for now and make changes after the training session.