client-side analytics
multiparty/web-mpc pull request #106
Opened 2019-02-13 21:24 UTC by lucyq

2019-02-13 22:06 UTC, lucyq commented
- Pre-fill spreadsheet vs. manual data entry
- Time spent on: page, session area, table area, review/submit area, each table relevant to submission
- Validation errors
- Browser

2019-02-14 00:20 UTC, lucyq commented
Tested & ready for merge now!

2019-02-14 05:33 UTC, lucyq commented
@frederickjansen please merge :D

2019-02-14 11:53 UTC, frederickjansen requested changes

2019-02-14 11:53 UTC, frederickjansen commented on client/app/helper/mpc.js
> +    return { tables, questions, usability };
Won't work in IE11

2019-02-14 11:57 UTC, frederickjansen approved these changes

2019-02-14 11:57 UTC, merged