Updates submission feedback using alertify to address #5.
multiparty/web-mpc pull request #11
Opened 2017-06-01 20:42 UTC by jgyou-bu

Includes submission history at the bottom of the page.

2017-06-07 17:09 UTC, frederickjansen requested changes

2017-06-07 17:09 UTC, frederickjansen commented on client/index.html
> +  <script type="text/javascript" src="style/alertify/alertify.js"></script>
Why are we loading this from the style folder, then again from the script folder?

2017-06-07 17:09 UTC, frederickjansen commented on client/index.html
> +  <script type="text/javascript" src="style/alertify/alertify-defaults.js"></script>
Same thing here.

2017-06-07 17:09 UTC, frederickjansen commented on client/index.html
> +  <link rel="stylesheet" type="text/css" href="style/alertify/css/themes/alertify-bootstrap.css">
Two more duplicates? See line 26.

2017-06-07 17:09 UTC, frederickjansen commented on client/script/ssCreate.js
> +    convertToHTML(submitEntries)
Add semicolon

2017-06-07 17:09 UTC, frederickjansen commented on client/script/ssCreate.js
> +    alertify.alert("<img src='style/accept.png' alt='Success'> Success!", "&nbsp Submitted data.");
Do we need a non-breakable space here? Why not use CSS for positioning? Otherwise use semicolon at end.

2017-06-07 17:09 UTC, frederickjansen commented on client/script/ssCreate.js
> +      alertify.alert("<img src='style/cancel.png' alt='Error'>&nbsp Error!",  err.responseText);
Same comment about nbsp, also line 358, 360, 458, 463.

2017-06-07 17:09 UTC, frederickjansen commented on client/script/ssCreate.js
> +            alertify.alert(errMsg);
What happens here to the styling of the alert? If this is an error message, why not use the error image that's used elsewhere?

2017-06-07 17:09 UTC, frederickjansen commented on client/script/ssCreate.js
> +    submitEntries.push({"Time": submitTime, "Submitted": false});
Should use lowercase keys, and no quotes in JS.

2017-06-07 17:09 UTC, frederickjansen commented on client/script/ssCreate.js
> +          alertify.alert("Error", errMsg);
Same question about consistency of styling alert box.

2017-06-08 14:11 UTC, jgyou-bu commented on client/index.html
> +  <script type="text/javascript" src="style/alertify/alertify.js"></script>
@frederickjansen - thanks for the feedback. I made changes that should address your comments. Let me know if anything else needs to be changed.

2017-06-14 16:36 UTC, merged