The new format for Handsontable plus the new tables from latest BWWC spreadsheets
multiparty/web-mpc pull request #20
Opened 2017-06-20 15:53 UTC by KinanBab

Manually merged master into branch (in the commit before last).

Disclaimer: there are a bunch of small/useless commits on the 16th. I could not install mongo on the lab machine (no sudo access), so I used a free Amazon Ec2 instance for testing. I used the repo to transfer code quickly between the local machine where I was editing, the ec2 instance where I was testing. Sorry for the horrible commit history.

2017-06-23 15:44 UTC, frederickjansen requested changes

2017-06-23 15:44 UTC, frederickjansen commented on client/index.html
>    <div id="board">
Remove commented out block

2017-06-23 15:44 UTC, frederickjansen commented on client/index.html
> +          <label><input autocomplete="off" type="radio" name="optradio" value="NA" checked='checked'>Do not wish to answer</label>
Double quotes

2017-06-23 15:44 UTC, frederickjansen commented on client/index.html
> +          var table_index = index_map[table.__sail_meta.name];
Use one underscore for private vars

2017-06-23 15:44 UTC, frederickjansen commented on client/script/client.js
> +  var _ = function validate_callback(i) {
Use IIFE to call function

2017-06-23 15:44 UTC, frederickjansen commented on client/script/client.js
> +  var session = $('#sess').val();
Trim session and email

2017-06-23 15:44 UTC, frederickjansen commented on client/script/client.js
> +  var data_submission = { 'questions': {} };
No quotes for JS objects

2017-06-23 15:44 UTC, frederickjansen commented on client/script/client.js
> +    var question_text = $($(questions[q]).find('.question-text')[0]).text();
Possible to write this cleaner?

2017-06-23 15:44 UTC, frederickjansen commented on client/script/client.js
> +  console.log(data_submission);
Remove log statements

2017-06-23 15:44 UTC, frederickjansen commented on client/script/client.js
> +  var data = shares['service'];
Consistent naming of shares (not sure what way to go)

2017-06-23 15:44 UTC, frederickjansen commented on client/script/client.js
> +      console.log(submission);
Remove log

2017-06-23 15:44 UTC, frederickjansen commented on client/script/client.js
> +        type: "POST", url: target_url,
Hardcode url

2017-06-23 15:44 UTC, frederickjansen commented on client/script/client.js
> +    console.log(response);
Remove log

2017-06-23 15:44 UTC, frederickjansen commented on client/script/client.js
> +    return response;
Don't need this?

2017-06-23 15:44 UTC, frederickjansen commented on client/script/client.js
> +    console.log(err);
Remove log

2017-06-23 15:44 UTC, frederickjansen commented on shared/mpc.js
> +  var fields = db ? function(x){ if(x.fields !== undefined) return x.fields; else return x;} : function(x){return x;};
Add comment

2017-06-23 15:44 UTC, frederickjansen commented on shared/mpc.js
> +  // TODO FIX WEIRD BEHAVIOR
Remove TODO

2017-06-23 15:44 UTC, frederickjansen commented on shared/mpc.js
> +  var agg = function initialize(obj) {
Merge with invalidCount function

2017-06-23 15:44 UTC, frederickjansen commented on shared/sail_hot.js
> +var validators_map = {
More comments please

2017-06-23 15:44 UTC, frederickjansen commented on shared/sail_hot.js
> + * Change the read only attribute of the entire table.
Change comment

2017-06-23 15:44 UTC, frederickjansen commented on shared/sail_hot.js
> +  $('#' + table.element + "-name").html(table.name);
Remove jQuery dependency

2017-06-26 15:03 UTC, KinanBab commented
@frederickjansen Addressed all comments.

2017-06-27 02:28 UTC, merged